name: Astronomer Deploy DAGs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Astro CLI
        run: curl -sSL https://install.astronomer.io | sudo bash -s

      - name: Deploy DAGs to Astronomer
        env:
          ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
          ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}
        run: |
          mkdir -p .astro
          echo "context: cloud.astronomer.io" > .astro/config.yaml
          astro deploy cmrfaz23f4la501nvg87gfssw --dags --force --workspace-id cmrf9nhxu4itb01naaus61yoc
